services:
  # Angular frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # On Mac/Windows, use extra_hosts to access host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
