import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';

/**
 * Service to handle article exports (PDF, Markdown, etc.)
 */
@Injectable({
  providedIn: 'root'
})
export class ExportService {
  private readonly http = inject(HttpClient);
  private readonly baseUrl = environment.baseApiUrl;

  /**
   * Export an article to PDF
   * Downloads the PDF file generated by the backend
   *
   * @param articleId - ID of the article to export
   * @returns Observable<Blob> - PDF file as blob
   */
  public exportArticleToPdf(articleId: number): Observable<Blob> {
    return this.http.get(`${this.baseUrl}/articles/${articleId}/export/pdf`, {
      responseType: 'blob',
      observe: 'body'
    });
  }

  /**
   * Trigger browser download of a blob file
   *
   * @param blob - File blob to download
   * @param filename - Name of the file to save
   */
  public downloadFile(blob: Blob, filename: string): void {
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    window.URL.revokeObjectURL(url);
  }

  /**
   * Generate filename for exported article
   * Format: article-{id}-{sanitized-title}.pdf
   *
   * @param articleId - Article ID
   * @param title - Article title
   * @returns Sanitized filename
   */
  public generatePdfFilename(articleId: number, title: string): string {
    // Sanitize title: remove special chars, replace spaces with hyphens
    const sanitizedTitle = title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // Remove accents
      .replace(/[^a-z0-9\s-]/g, '') // Remove special chars
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single
      .slice(0, 50); // Limit length

    return `article-${articleId}-${sanitizedTitle}.pdf`;
  }
}
